//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stardome.DomainObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public int UserId { get; set; }
        public int FolderId { get; set; }
        public Nullable<System.DateTime> DateGiven { get; set; }
        public Nullable<System.DateTime> DateTaken { get; set; }
        public int Id { get; set; }
    
        public virtual Folder Folder { get; set; }
        public virtual UserAuthCredential UserAuthCredential { get; set; }
    }
}
