//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stardome.DomainObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int ActionId { get; set; }
        public string Description { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual UserAuthCredential UserAuthCredential { get; set; }
    }
}
